

# Executive Summary {-}

This document can be considered a living document.  Version numbers are logged for each release with modifications, enhancements and other changes tracked [here](https://github.com/NewGraphEnvironment/fish_passage_parsnip_2021_reporting/blob/master/NEWS.md) with issues and proposed/planned enhancements tracked [here](https://github.com/NewGraphEnvironment/fish_passage_parsnip_2021_reporting/issues). 

<br>

The health and viability of freshwater fish populations can depend on access to tributary and off channel areas which provide refuge during high flows, opportunities for foraging, overwintering habitat, spawning habitat and summer rearing habita. As road crossing structures are commonly upgraded or removed there are numerous opportunities to restore connectivity by ensuring that fish passage considerations are incorporated into repair, replacement, relocation and deactivation designs. 

<br>

The Society for Ecosystem Restoration in Northern BC (SERNbc) is working together with the McLeod Lake Indian Band, the Peace Region Fish and Wildlife Compensation Program (FWCP), the Provincial Fish Passage Technical Working Group (FPTWG), road/rail tenure holders and other FWCP stakeholders/partners to prioritize, plan and fund the restoration of fish passage at Parsnip River watershed road crossing structure barriers. 

<br>

This project builds on Society for Ecosystem Restoration Northern BC (SERNbc) work in 2019 - 2020 which can be referenced [here](https://newgraphenvironment.github.io/Parsnip_Fish_Passage/) [@irvine2020ParsnipRiver]. In 2019, following a literature review, analysis of fish habitat modelling data, the Provincial Stream Crossing Inventory System (PSCIS) and a community scoping exercise within the McLeod Lake Indian Band habitat confirmation assessments were conducted at 17 sites throughout the Parsnip River watershed with 10 crossings rated as high priorities for rehabilitation and three crossings rated as moderate priorities for restoration.

<br>

In 2021/2022, through this collaborative project, and leveraging numerous other connectivity restoration initiatives underway throughout the province, we were able to source funding from the Ministry of Forests, Lands and Natural Resource Operations and Rural Development to catalyze project activities including initiation of the replacement of a high priority crossing in the Missinka River watershed (PSCIS crossing 125179 on the Chuchinka-Missinka FSR) with a clearspan bridge.  Through financial support from FWCP and the Fish Passage Technical Working Group, as well as in-kind and monetary support from Sinclar Group Forest Products, remediation of fish passage at this site will be completed in 2022.  Additionally, works at another high priority site identified in 2020 (PSCIS crossing 125000 on the Chuchinka-Arctic FSR) will be initiated. British Columbia Timber Sales is planning to deactivate the Chuchinka-Colbourne FSR between the location of high priority crossing PSCIS 125345 on a tributary to the Parsnip River and the Chuchinka-Anzac FSR. The work is schedule for July and August of 2022.  Working with BCTS and McLeod Lake we have been in contact with CN Rail to advocate for the removal of crossing 57687 under the railway immediately upstream of the PSCIS crossing 125345 and the Chuchinka-Colbourne FSR. Discussions are ongoing, and it is hoped that action will be taken by CN this summer to remediate crossing 57687 before the access road from the south is deactivated. 

<br>

Through the ongoing development of open source analysis and data presentation tools we are identifying and highlighting additional sites with potential connectivity issues and are planning on the ground works to assess opportunities, build the capacity and provide the data necessary to implement and monitor restoration actions.  Planning, field assessments and follow up reporting will continue to include engagement with road/rail/forest tenure holders, build awareness for connectivity issues in the wider community and build capacity for ecosystem restoration in the Peace Region. 


<br>

We are leveraging this project together with numerous others to contributing to the open source development of [`bcfishpass`](https://github.com/smnorris/bcfishpass), [`fwapg`](https://github.com/smnorris/fwapg), [`bcdata`](https://github.com/smnorris/bcdata), [bcfishobs](https://github.com/smnorris/bcfishobs) and [`fpr`](https://github.com/NewGraphEnvironment/fpr).  We are using these database building, habitat/connectivity modeling and data presentation tools to conduct reproducible analysis/presentation of fish passage restoration opportunities in the Peace Region in order to facilitate outreach, prioritize sites and provide the background information necessary to communicate restoration plans/actions effectively. 

<br>

As there have been significant advancements in our ability to scope for restoration opportunities since the 2019 habitat confirmations were conducted in the Parsnip River watershed (ie. `bcfishpass` outputs such as the bull trout spawning and rearing model developed in part through this project) we built a prototype of an interactive map/table widget tool to facilitate planning for future field surveys in the Peace Region. The interactive interface allows screening of previously inventoried as well as modelled stream crossing locations based on PSCIS information as well as the likely amount and type of habitat modelled upstream.  Users can download csv results from those screening processes as well as associated georeferenced field maps to facilitate field surveys. 

<br>

Field surveys planned for 2022 and beyond will contribute to McLeod Lake Indian Band capacity building programs, helping facilitate the continued evolution back to indigenous led natural resource management and stewardship within their traditional territory. On the ground research and monitoring is an essential part of any restoration program and is necessary to ensure that we identify the best and most efficient opportunities for fish passage restoration while incorporating adaptive management informed by traditional knowledge and real-time planning/monitoring data.

<br>

Updated maps for the Parsnip River, Carp River and Crooked River watershed groups incorporating the newly developed sa'ba (bull trout) spawning and rearing habitat model are available [here](https://hillcrestgeo.ca/outgoing/fishpassage/projects/parsnip/archive/2022-05-27/). 

<br>

An online connectivity mapping portal for the Peace Region has been launched and is located [here](https://newgraphenvironment.github.io/fish_passage_parsnip_2021_webmap). At the time of reporting the site was undergoing development with the interface expected to evolve significantly over the coming months.  Future layers to be added to map include fisheries observations, the  [Recreational Opportunity Spectrum Inventory data](https://catalogue.data.gov.bc.ca/dataset/recreational-opportunity-spectrum-inventory), hydrometric station locations, historic fish sampling sites, wetlands, etc.  

<br>

Although remediation and replacement of stream crossing structures can have significant benefits to local fish populations, the costs of remedial works can be significant and the impacts of the work often complex to evaluate and quantify. Additionally, allocation of ecosystem restoration funding towards infrastructure upgrades on transportation right of ways are not always considered ethical under all circumstances from all perspectives. When funds are finite and invested groups are engaged in fund raising, cost benefits and the ethics of crossing replacements should be explored collaboratively alongside the cost benefits and ethics of alternative investment activities including transportation corridor relocation/deactivation, land procurement/covenant, cattle exclusion, riparian/floodplain restoration, habitat complexing, water conservation, commercial/recreational fishing management, instream infrastructure removal and research.
