

# Recomendations{-}

A multi-year plan with one to two structure replacements (or removals) each year with works at each site phased over two years each is recommended.  This approach will facilitate progress at a minimum of one site per year and allows ample time for planning, coordination and funding acquisition related to each restoration. Multi-year planning allows an inclusive environment to solicit funding collaboration with the numerous potential partners and stakeholders in the watershed (i.e. Sinclar, Canfor, CN Rail, Coastal Gas Link, FLNR, fish passage technical working group, Ministry of Transportation and Infrastructure, McLeod Lake, Treaty 8 Nations, etc.).
 
 * In 2023/2024 we propose replacement of crossings where preparations were made in 2022/2023 in partnership with Sinclar.  Sinclar has committed to obtaining portions of the funding for this work through the forestry appraisal system and we will actively engage with partners and stakeholders to obtain other funding contributions.  Additionally, we propose preparations for structure replacement at  addition sites that can be completed in the upcoming years.
 
 * In 2022/2023  we will work together with BCTS and other interested parties to rehabilitate and monitor the Chuchinka-Colbourne FSR where 125345 (Tributary to Parsnip River) will be removed and the road deactivated/decompacted and planted in 2022.  We will continue to engage with CN to advance remediation of passage at crossing 57687 located under the railway immediately upstream of this site.
 
  * We recommend continuing to engage FWCP partners and stakeholders to explore and clearly communicate fish passage issues in the Parsnip River watershed, build relationships and obtain partnership funding commitments while collaboratively prioritizing, planning and delivering fish passage restorations.
 
  * We recommend continuing to implement capacity building programs that will provide resources and skills for watershed stakeholders and partners to engage in watershed restoration planning activities and on the ground works as well as to monitor outcomes of project initiatives.  
 
 
  * Refine barrier thresholds for road-stream crossing structures to explore metrics specific to life stage and life history types of species of interest. This will further focus efforts of potential remediation actions based on biological attributes (ex. timing of migration, size/direction of fish migrating, population dynamics, etc.) and could result in the consideration of interim "stop-gap" physical works to alter crossing characteristics that can address key connectivity issues yet be significantly less costly than structure replacements (ex. building up of downstream area with rock riffles to decrease the outlet drop size and/or increasing water depth within pipe with baffles and substrate additions).
  
  * Continue to develop `bcfishpass`,`bcfishobs`, `fwapg`, `bcdata`, `fpr` and the web mapping portal to share open source data analysis and presentation tools that are scaleable, leverage forward years of investments from numerous contributors and facilitate continual improvement.  Tools should continue to be flexible and well documented to allow the future incorporation of alternative fragmentation indicators, habitat gain/value metrics and watershed sensitivity indicators. We recommend continuing to work with Ministry of Environment and First Nations governments to develop an evidenced based approach to the quantification of potential habitat gains through fish passage remediation and update data collection/storage protocols to ensure data collected can be utilized as effectively as possible to inform natural resource management.
  
  * Continue to increase awareness of the Provincial Stream Crossing Inventory Summary System and `bcfishpass` and the need to commit to the use of standardized tools by all parties and collaborators to ensure that the installation and repair of new and historic infrastructure incorporate known data and defensible fisheries science into prioritization/design/implementation/monitoring.
    
  * Continue to collaborate with potential partners to build relationships, explore perspectives and develop “road maps” for aquatic restoration in different situations (MoT roads, rail lines, permit roads of different usages, FSRs, etc.) – documenting the people involved, discussions and processes that are undertaken, funding options, synergies, measures of success, etc. 
 
 
